name: "Go-build"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: "Go-build"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Setup Go
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.18' # The Go version to download (if necessary) and use.

      # Install all the dependencies
      - name: Install dependencies
        run: |
          go version
          go get -u golang.org/x/lint/golint

      # Run vet on the code
      - name: Run vet & lint
        run: |
          go vet ./...

      # Run testing on the code
      - name: Run testing
        run: go test -v ./...

      # Run build of the application
      - name: Run build
        run: make all

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: .out
          path: .out
          retention-days: 5