name: "Terraform"

on:
  workflow_run:
    workflows: ["Go-build"]
    types:
      - completed

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    env:
      ## Environment variables
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION:  ${{ secrets.AWS_DEFAULT_REGION }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: ${{ github.event.workflow_run.workflow_id }}
          workflow_conclusion: success

      - name: List downloaded artifacts
        run: ls -la

      - name: List artifacts folfer
        run: cd .out && ls -la

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          # terraform_version: 0.13.0:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Format
        id: fmt
        run: terraform -chdir=infra fmt -check

      - name: Terraform Init
        id: init
        run: |
          terraform -chdir=infra init \
          -backend=true \
          -backend-config="key=sms-gateway-server/prd-terraform.tfstate" \
          -force-copy

      - name: Terraform Validate
        id: validate
        run: terraform -chdir=infra validate -no-color

      - name: Terraform Plan
        id: plan
        run: terraform -chdir=infra plan -no-color -input=false

      - name: Terraform Apply
        id: apply
        run: terraform -chdir=infra apply -auto-approve -input=false